language: haskell

sudo: false

# We test against different Stackage snapshots.
matrix:
  include:
    - env: BUILD=stack STACK_YAML=stack.yaml

    - env: BUILD=stack STACK_YAML=stack-lts-1.15.yaml

addons:
  apt:
    packages:
    - python
    - python-numpy

before_install:
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis-setup.sh
 - stack install hlint --fast

install:
 - stack --no-terminal test --only-dependencies --fast

script:
 - echo "travis_fold:start:SCRIPT Build Futhark compiler"
 - stack --no-terminal test --haddock --no-haddock-deps --fast
 - echo "travis_fold:end:SCRIPT Built Futhark compiler"
 - echo "travis_fold:start:SCRIPT Installing Futhark compiler"
 - stack install
 - echo "travis_fold:end:SCRIPT Installed Futhark compiler"

# Now for integration testing
 - data/runtests.sh # Run integration test suite.
 - data/runtests.sh --compiler=futhark-py --exclude=no_python -c # Run integration test suite with Python code generator.
 - data/runtests.sh -t --exclude=no_opencl --compiler=futhark-pyopencl # Also test OpenCL code generation

 # Let us try checking out the benchmark suite for some more tests.
 - git clone https://github.com/HIPERFIT/futhark-benchmarks.git
 - (cd futhark-benchmarks && futhark-test --travis $(find . -name '*.fut') && futhark-test --travis -t --compiler=futhark-pyopencl $(find . -name '*.fut'))

 - if [ "$STACK_YAML" = stack.yaml ]; then tools/style-check.sh src; fi # Check for style issues.

cache:
  directories:
    - $HOME/.stack

# EOF
