language: haskell

sudo: false

# We test against different Stackage snapshots.
env:
 - STACK_YAML=stack.yaml
 - STACK_YAML=stack-lts-1.15.yaml

addons:
  apt:
    packages:
    - hlint
    - python
    - python-numpy

install:
 - stack setup --stack-yaml $STACK_YAML
 - stack build --stack-yaml $STACK_YAML --only-dependencies

script:
 - stack build --stack-yaml $STACK_YAML
 - stack test --stack-yaml $STACK_YAML
 - stack install --stack-yaml $STACK_YAML

 - cabal check

 - data/runtests.sh # Run integration test suite.
 - data/runtests.sh --compiler=futhark-py --exclude=no_python -c # Run integration test suite with Python code generator.
 - data/runtests.sh -t --exclude=no_opencl --compiler=futhark-pyopencl # Also test OpenCL code generation

 # Let us try checking out the benchmark suite for some more tests.
 - git clone https://github.com/HIPERFIT/futhark-benchmarks.git
 - (cd futhark-benchmarks && futhark-test --travis $(find . -name '*.fut') && futhark-test --travis -t --compiler=futhark-pyopencl $(find . -name '*.fut'))

 - tools/style-check.sh src # Check for style issues.
 - stack haddock # Can we build the documentation?

# EOF
